main: bubbleimprove fibsingle sepnotes
bubbleimprove: bubbleimprove.c
	gcc -o bubbleimprove bubbleimprove.c 
fibsingle: fibsingle.c
	gcc -o fibsingle fibsingle.c 
sepnotes: sepnotes.c
	gcc -o sepnotes sepnotes.c 
clean: 
	rm bubbleimprove fibsingle sepnotes
