all: largest_smallest.exe arithmetic.exe comparing_integers.exe
largest_smallest.exe: largest_smallest.c
	gcc -o largest_smallest.exe largest_smallest.c
arithmetic.exe: arithmetic.c
	gcc -o arithmetic.exe arithmetic.c
comparing_integers.exe: comparing_integers.c
	gcc -o comparing_integers.exe comparing_integers.c
clean: 
	rm largest_smallest.exe arithmetic.exe comparing_integers.exe;