main: float_to_dollars.exe grosssalary.exe swap_num.exe
float_to_dollars.exe: float_to_dollars.c
	gcc -o float_to_dollars.exe float_to_dollars.c
grosssalary.exe: grosssalary.c
	gcc -o grosssalary.exe grosssalary.c
swap_num.exe: swap_num.c
	gcc -o swap_num.exe swap_num.c
clean: 
	rm float_to_dollars.exe grosssalary.exe swap_num.exe