main: electricity_bill.exe leap_year.exe total_grade.exe
electricity_bill.exe: electricity_bill.c
	gcc -o electricity_bill.exe electricity_bill.c
leap_year.exe: leap_year.c
	gcc -o leap_year.exe leap_year.c
total_grade.exe: total_grade.c
	gcc -o total_grade.exe total_grade.c
clean: 
	rm electricity_bill.exe leap_year.exe total_grade.exe