main: classarr largesmallarr maxelement oddeventhird reversearr5 reversearrany
classarr: classarr.c
	gcc -o classarr classarr.c
largesmallarr: largesmallarr.c
	gcc -o largesmallarr largesmallarr.c
maxelement: maxelement.c
	gcc -o maxelement maxelement.c
oddeventhird: oddeventhird.c
	gcc -o oddeventhird oddeventhird.c
reversearr5: reversearr5.c
	gcc -o reversearr5 reversearr5.c
reversearrany: reversearrany.c
	gcc -o reversearrany reversearrany.c
clean: 
	rm classarr largesmallarr maxelement oddeventhird reversearr5 reversearrany